
package fooddata.adapter.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RetrieveInterface", targetNamespace = "http://service.adapter.fooddata/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RetrieveInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<fooddata.adapter.service.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://service.adapter.fooddata/", className = "fooddata.adapter.service.GetProducts")
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://service.adapter.fooddata/", className = "fooddata.adapter.service.GetProductsResponse")
    @Action(input = "http://service.adapter.fooddata/RetrieveInterface/getProductsRequest", output = "http://service.adapter.fooddata/RetrieveInterface/getProductsResponse")
    public List<Product> getProducts(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
